config.sh.example, letsencrypt.sh
- move BASEDIR further up in the config file
- make private key a config option
- fix logic if private key is specified via command line option
- start using PARAM_* for parameters provided at the command line
=> fix logic if private key is specified via command line option

config.sh.example, letsencrypt.sh
When deploying your script, I found that you are using SCRIPTDIR as fall-back directory. This is very error-prone, and completely unnecessary (as BASEDIR defaults to SCRIPTDIR).
For security sake, NOTHING should be relative to SCRIPTDIR, not even the config.sh file location (I did not patch this as it would change the basic bahaviour).
Some further suggestions:
- use only one default location for config.sh (e.g. /etc/letsencrypt.sh/config.sh), as an attacker can do nasty stuff if he gets access on any of the config locations
- don't use default config if config.sh is not found, as this does most probably break things for most users
=> Don't use SCRIPTDIR

letsencrypt.sh
When overriding PRIVATE_KEY in config.sh, letsencrypt.sh erroneously changes it back to "${BASEDIR}/private_key.pem"
=> bugfix: keep configured PRIVATE_KEY

letsencrypt.sh, test.sh
$ ./letsencrypt.sh --domain test1.com --domain test2.com -c
Only one command can be executed at a time.
See help (-h) for more information.
This is obviously wrong. Fixed it.
=> fix: --domain/-d is a parameter and not a command!

test.sh
My fork failed on travis-ci due to this typo in the test.sh (ngrog vs ngrok). Now the test runs smoothly.
=> fix typo in test.sh (ngrok not found)

README.md, config.sh.example, letsencrypt.sh
This adds support for the new dns-01 challenge! (try 2)
ATTENTION: This challenge is currently only available in staging, see: https://community.letsencrypt.org/t/dns-challenge-is-in-staging/8322
I am uncertain if "urlbase64" is the correct way in this case or if this should be a "base64 -w0".
See also: https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-7.5
=> add support for dns-01 challenge - try 2

config.sh.example
The `~/.letsencrypt.sh/config.sh` path is not checked anymore since ff11639 (#67). This removes it from the `config.sh.example` as it might confuse users.
=> Remove home path from config.sh.example

letsencrypt.sh
I could've sworn the script gave me an  `exit1: command not found` error at some point, but I can't reproduce it now.
In any case, here is the world's smallest bugfix.
=> Added missing space before exit code.

letsencrypt.sh
There's no need to create the challenge directory when using dns-01, so this commit adds a check to avoid that.
=> Require $WELLKNOWN only when using http-01.

letsencrypt.sh
Problem
=======
If BASEDIR is set in config.sh, this does not modify the (default) values
of either PRIVATE_KEY, WELLKNOWN or LOCKFILE. One needs to manually specify
those three config variables in config.sh, if a different BASEDIR
should be used by letsencrypt.sh.
How to reproduce
----------------
1. Clone letsencrypt.sh to /tmp/
`cd /tmp/ && git clone https://github.com/lukas2511/letsencrypt.sh.git`
2. Provide the following /tmp/letsencrypt.sh/config.sh:
```
BASEDIR="/tmp"
#WELLKNOWN="${BASEDIR}/.acme-challenges"
#PRIVATE_KEY="${BASEDIR}/private_key.pem"
```
3. Run letsencrypt.sh with paramemetr -e
`/tmp/letsencrypt.sh/letsencrypt.sh -e`
```
declare -- CA="https://acme-v01.api.letsencrypt.org/directory"
declare -- LICENSE="https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf" …
```
=> Respect configured BASEDIR for default values

letsencrypt.sh
The pattern
```
VAR="$(cmd '"')"
```
breaks syntax highlighting in some editors (e.g. gedit or jedit) due to
the tripple double quotes.
=> Fix possibly broken syntax highlighting

config.sh.example, letsencrypt.sh
This PR adds support for a new config variable CONFIG_D in the main
configuration file. Setting a path to a directoy for CONFIG_D advises
letsencrypt.sh to source any additional files found in the specified
CONFIG_D directory, that have a '.sh' ending.
By default CONFIG_D is not set, meaning letsencrypt.sh does not source any
additional configuration files.
> ### Background
> From the perspective of a Linux distribution, letsencrypt.sh should be shipped
> with a default configuration located at /etc/letsencrypt.sh/config.sh. Neither
> the user nor other packages should need to mangle this default configuration.
> Instead configuration changes should go into separate files.
=> Add conf.d support

README.md, letsencrypt.sh
I was looking for a Let's Encrypt client to integrate in to an existing automation tool. Your `letsencrypt.sh` implementation came closest. However, it still does too much.
This pull requests splits out the core functionality (sign a CSR) from the nice-to-have features (generate a CSR from the `domains.txt` file), and exposes this functionality from the command line.
The newly added `--signcsr` command does exactly what its name implies: it extracts the domain names from the CSR (SANs or CN), requests and executes the challenge for each one, requests the CRT, and outputs that to stdout (normal output is redirected to stderr for this command).
=> Add ability to sign "arbitrary" CSRs

letsencrypt.sh
closes #101 
Verified with following test-hook:
```
#!/bin/bash
echo "Args:"
for a
do
echo "$a"
done
echo "Press return"
read
```
BTW: In contrast to the official client your script is a delight (and just works).  Thanks!
=> pass IO descriptors to HOOK transparently

README.md
There is currently no mention of Let’s Encrypt rate limits or the staging server. I’ve updated the readme so that the rate limit notice is prominently displayed and the necessary config setting to use the staging server is included in the instructions.
=> Updated Readme with rate limit warning + staging URL

letsencrypt.sh
I had symlinks to some files in my `certs` folder, for each of them a folder was created in the `archive` directory. This pull request skips all non-folder entries in `certs` when running cleanup.
=> Skip non-folder entries on cleanup.

config.sh.example, hook.sh.example, test.sh
On FreeBSD bash is installed in `/usr/local/bin`; this patch alters the shebang to use `/usr/bin/env bash` instead, to ensure that the shell scripts work on (particularly) the *BSDs as well.
=> Use /usr/bin/env bash shebang

.gitignore, hook.sh.example, letsencrypt.sh
Some services need the `chain.pem` file for configuration, simply passing that path to the hook script is probably cleaner than getting the path from the `fullchain.pem` file by doing `CHAINFILE=${4/full/}`.
=> Pass intermediate cert to hook script

letsencrypt.sh
This fixes cases where `*.foo` expands to the string `*.foo` instead of an empty string if no matching files exist.
I know this is a problem with my setup, but it would be nice if letsencrypt.sh could handle such cases gracefully ;-)
Error without the change (I have a `chain.pem` in `customfolder`):
```
Moving unused file to archive directory: customfolder/chain-*.pem
mv: cannot stat '/path/to/customfolder/chain-*.pem': No such file or directory
```
=> Handle case where no files to cleanup exist.

hook.sh.example, letsencrypt.sh, test.sh
In my scenario, where I automate certificate-issuance through the `letsencrypt.sh`-client, I need to also have a hook for all certificates, of which the domains haven't changed and which are still valid.
I tried to integrate this functionality, as I think more people could benefit from this feature.
As far as I am concerned, it works as expected.
I'd greatly appreciate if you could merge this pull-request.
Thanks,
Leon
=> Add hook for unchanged certificates.

.gitignore, config.sh.example, letsencrypt.sh
In some cases you need your registration id,
for example if you want to request a rate limit exception.
So keep the new-reg output on disk.
=> Keep registration information as json.

docs/wellknown.md
I spent a few hours fiddling with an invalid challenge, because I had assumed the acme-challenge part was added automatically. This change should help future users not make the same mistake.
=> wellknown.md: Clarify WELLKNOWN variable

docs/examples/config.sh.example, letsencrypt.sh
> This is a follow up from: https://bugs.debian.org/824928
In the [Debian packaging of letsencrypt.sh](https://packages.debian.org/letsencrypt.sh) we would like to have the file listing the domains for which certificates should be requested at: `/etc/letsencrypt.sh/domains.txt`.
Best thing to accomplish this in our opinion is to make it possible to define `${DOMAINS_TXT}` in config.sh.
This pull request implements this feature.
=> Make location of domains.txt configurable

README.md, docs/examples/config, letsencrypt.sh
Particularly useful if you want to set up dual certificates, you can set the config files to output into separate directories rather than using separate base directories for each. e.g. `CERTDIR="${BASEDIR}/certs/rsa"` and `CERTDIR="${BASEDIR}/certs/ecdsa"`
=> Make certificate output location configurable

letsencrypt.sh
Previously, if you have a directory called config in any of the check_config locations and had not specified one manually the the script would hit an error
```
./letsencrypt.sh: line 89: .: /home/acme/letsencrypt.sh/config: is a directory
```
=> Check that the detected config is a file

letsencrypt.sh
In case curl gives an error, it's helpful to know the URL
being tried and the method. In the GET case, one can easily
retry in the shell and debug this.
=> Include method and URL in curl error

letsencrypt.sh
As I like to keep all my configuration at the same place (/etc/letsencrypt.sh/) in this case I've created a patch to have the location of the per-cert configuration files configurable. I use this to this per-cert configuration files in /etc/letsencrypt.sh/domains.d/{domain name} in stead of /var/lib/letsencrypt.sh/certs/{domain name}.
=> Introduce per cert configuration directory DOMAINS_D

CHANGELOG, README.md, docs/examples/config, letsencrypt.sh
Issue is:
Name resolves to bunch of an IPv4 and IPv6 addresses, but IPv6 is unreachable from network.
Hence --ipv4 is passed to curl.
=> Added option to select IP version of name to address resolution

docs/ecc.md
Let's Encrypt will however sign all ECDSA certs with an RSA intermediate certificate.
https://letsencrypt.org/upcoming-features/
=> ECDSA is supported since February 10, 2016

docs/examples/hook.sh
use plain shell syntax,
also protect against if arguments contain spaces.
=> examples/hook: no bashism

docs/wellknown.md
at least in 1.4 the syntax is `server.modules` and it's an array.
and it's always good idea to keep trailing comma to avoid syntax errors when adding new entries.
=> fix lighttpd syntax

dehydrated, docs/examples/config, test.sh
Hi Lukas!
Implementation of private key rollover
Currently uses $PRIVATE_KEY_ROLLOVER, should work for per-cert config.
To use:
PRIVATE_KEY_RENEW=yes
PRIVATE_KEY_ROLLOVER=yes
An extra private key is created on the first run.
If a rolloverkey and a private key exists, it swaps both.
If PRIVATE_KEY_ROLLOVER is disabled, rollover keys are deleted.
No changes to HOOK-api.
Hacked some CI-tests, but untested.
They should:
a) request a cert, create a private key [A], create a rollover key [B].
b) request a cert (forced), create a private key [C], swap rollover key [B] with private key [C]
c) Check if SHA256 Hash matches with [B] (actual private key used on b) should match rollover key in a) )
=> Basic implementation for private key rollover

dehydrated
For domains that are already validated we don't need to fulfill further challenges.
If a challenge request for a domain returns `"status": "valid"` no further validation is required and further processing is skipped. Skipping this further processing also avoids parsing problems when the challenge response contains additional fields, for example describing a previous successful DNS challenge.
The new variable `${challenge_altnames}` is used to keep track of the names that are not validated yet and still need do the challenge. When later iterating over this possibly empty array a `:0` substring expansion has to be used to avoid bash complaining about an unbound variable (it treats empty arrays as unset).
This solves the same problem as pull request #283, hopefully in a more robust way.
=> Skip challenge for already validated domains

dehydrated
This enables automation systems to run multiple instances of dehydrated
while still maintaining a locking facility. This is necessary for
projects like https://github.com/GUI/lua-resty-auto-ssl.
With this feature, one could run the script multiple times, while still
having a form of locking:
./dehydrated --lock-suffix test1.example.com -d test1.example.com
./dehydrated --lock-suffix test2.example.com -d test2.example.com
./dehydrated --lock-suffix test3.example.com -d test3.example.com
./dehydrated --lock-suffix test4.example.com -d test4.example.com
./dehydrated --lock-suffix test5.example.com -d test5.example.com
When starts the script with the same locking suffix, the scripts exits
like it normally would when locked. This will give you the benefits of
using --no-lock, without the …
=> Add new parameter --lock-suffix.

dehydrated, docs/dns-verification.md, docs/examples/hook.sh
This hook is called if the challenge response has failed, so domain owners can be aware and act accordingly.
=> Adding the invalid_challenge hook

dehydrated
When all names in a cert have already been validated, the challenge_altnames array will be empty, causes an error in later code. This patch adds a test to handle that case.
Tested with: GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
=> Test for case when challenge_altnames is empty

dehydrated, docs/dns-verification.md, docs/examples/hook.sh
This hook is called when a HTTP request fails (e.g., when the ACME server is busy, returns an error, etc). It will be called upon any response code that does not start with '2'. Useful to alert admins about problems with requests.
=> Adding the request_failure hook

dehydrated
it should split the filename on the last dot instead of the first
example of problem if you have a dot in your path (e.g. the dot in my username **a.loibl**):
```
$ dehydrated --account
+ Updating registration id: 11447865 contact information...
+ Backup /home/a.loibl/xxx/accounts/xxx/registration_info.json as /home/a-1508250049.json
cp: cannot create regular file ‘/home/a-1508250049.json’: Permission denied
```
with this change:
```
$ dehydrated --account
+ Updating registration id: 11447865 contact information...
+ Backup /home/a.loibl/xxx/accounts/xxx/registration_info.json as /home/a.loibl/xxx/accounts/xxx/registration_info-1508250417.json
+ Populate /home/a.loibl/xxx/accounts/xxx/registration_info.json
+ Done!
```
=> fix --account command backup file path generation

dehydrated
With the globbing changes made in 61083cf52231e09e3a9b599d602c06978704ec57 to globally disable globbing by default, this broke the ability to load the CONFIG_D `*.sh` files.
This re-enables globbing when reading these `*.sh` files and then disables it again afterwards. Note that this also keeps globbing enabled inside the loop, when sourcing the individual `*.sh` files for backwards compatibility (so if the individual config scripts relied on the default of globbing being enabled, there won't be any change in behavior).
=> Fix globbing of CONFIG_D *.sh files

dehydrated
Fixes #671. Note that I did not change the ACMEv1 code at all, not sure what that version of the protocol is supposed to do.
We store the account URL on account creation in the `account_id.json` file.
When reading the file, if the attribute is missing, we fall back to previous behaviour, with a warning message.
---
Per https://tools.ietf.org/html/rfc8555#section-7.3
> The server returns this account object in a 201 (Created) response, with the account URL in a Location header field.  The account URL is used as the "kid" value in the JWS authenticating subsequent requests by this account (see Section 6.2).  The account URL is also used for requests for management actions on this account, as described below.
=> Fix account URL

dehydrated
before applying heuristics, use `PRETTY_NAME` from os-release(3),
which reliably exists on all common linux distributions.
keep the /etc/issue parsing as fallback.
=> fix OS name detection
